version: 2

models:
  - name: stg_customer
    description: "customers dataset from raw.dec_raw.customers."
    columns:
      - name: customer_id
        description: "Unique customer identifier."
        tests: [not_null, unique]
      - name: full_name
      - name: email
      - name: join_date

  - name: stg_orders
    description: "orders dataset from raw.dec_raw.orders."
    columns:
      - name: order_id
        tests: [not_null, unique]
      - name: customer_id
      - name: order_date
      - name: total_amount

  - name: stg_order_items
    description: "Order line items from raw.dec_raw.order_items."
    columns:
      - name: order_item_id
        tests: [not_null, unique]
      - name: order_id
      - name: product_id
      - name: quantity
      - name: line_total

  - name: stg_products
    description: "Products dimension from raw.dec_raw.products."
    columns:
      - name: product_id
        tests: [not_null, unique]
      - name: product_name
      - name: category
      - name: price

  - name: stg_loyalty_points
    description: "Loyalty points from raw.dec_raw.loyalty_points."
    columns:
      - name: loyalty_id
        tests: [not_null, unique]
      - name: customer_id
      - name: points_earned
      - name: transaction_date
      - name: source
